# Site settings
title: Blog 
description: "Research blog"
url: "https://guillaumeorlando.github.io/"
author:
  name: "Guillaume Orlando"
  email: "guillaume.orlando@protonmail.com"
  url: "guillaumeorlando.github.io "

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variable
version: "2.1.2"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
